### PR TITLE
Updated Uno.Wasm.Bootstrap to 7.0.11

### LINKED ISSUE #318: Update Uno.Wasm.Bootstrap to latest version 7.x
### Describe the bug

# Background
In #297, we updated all Uno libraries to the latest version, except for [Uno.Wasm.Bootstrap](https://www.nuget.org/packages/Uno.Wasm.Bootstrap). 

According to the Uno Platform team:

> Uno.Wasm.Bootstrap 3.x is .NET6, and is using emscripten 2.0.23: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/fc89b40db92a14b8f04d4c5c9c72690bdcd7b878/src/Uno.Wasm.Bootstrap/Constants.cs#L19
> 
> Uno.Wasm.Bootstrap 7.x is .NET7, and is using emscripten 3.1.12: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/55a871e6ed4a255a93631f75d9edb6362356adbe/src/Uno.Wasm.Bootstrap/Constants.cs#L19

During #297, we found that `Rive.RiveSharp` could not be used with `Uno.Wasm.Bootstrap` 3.x as it was compiled with another version. This was corrected in #306.

# The problem
Labs is still using Uno.Wasm.Bootstrap 3.x, but needs to be using the latest version.

### Steps to reproduce

```text
n/a
```

### Expected behavior

n/a

### Screenshots

_No response_

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

_No response_

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

_No response_

### Visual Studio Build Number

_No response_

### Device form factor

_No response_

### Additional context

_No response_

### Help us help you

Yes, but only if others can assist.

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR closes CommunityToolkit/Tooling-Submodule#13 and is a simple version bump.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
This error is now showing properly in the binlogs:

```
[00:00:39.4181642] error: undefined symbol: _ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv (referenced by top-level compiled C/C++ code)
[00:00:39.4181652] warning: Link with `-sLLD_REPORT_UNDEFINED` to get more information on undefined symbols
[00:00:39.4181659] warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
[00:00:39.4181814] warning: __ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```

image

@csmartdalton this is coming from Rive, any ideas on what could be causing this?

**Review by niels9001 — APPROVED** [review]

**Comment by michael-hawker** [comment]
@Arlodotexe was this ready to be merged or is there still an issue with Codespaces even with the latest commit that the build passes now?

**Comment by Arlodotexe** [comment]
> @Arlodotexe was this ready to be merged or is there still an issue with Codespaces even with the latest commit that the build passes now?

See https://github.com/CommunityToolkit/Labs-Windows/issues/318#issuecomment-1386131563

**Comment by Arlodotexe** [comment]
This PR will be reopened in the submodule

**Pull request closed without merging**
