### PR TITLE
Fixed XAML Hot Reload for samples under UWP / VS 2022

### PR DESCRIPTION
**Pull request by Arlodotexe**
# Overview

This PR fixes an issue where Hot Reload wasn't working as expected. Changes to XAML code were not reflected in the running app.

Hot Reload now works as expected.

### CODE REVIEW

**Comment by michael-hawker** [comment]
I created a new page and got this, but it's still working on my other page, so I'm a bit confused...

image

I'll see if it persists when I rebuild.

**Comment by michael-hawker** [comment]
Hmm, actually I merged this into my branch and it doesn't seem to detect it still or work with hot reload (I did a git clean too after closing VS)

image

What VS version are you using?

**Comment by michael-hawker** [comment]
This may be another bug as I reverted this change back, and still saw this:

image

Funny thing is it worked fine in WindowsAppSDK, so specific to UWP?

**Comment by Arlodotexe** [comment]
Hot Reload is now working on main on my machine, without these code changes 🤔

**Pull request closed without merging**
