### PR TITLE
Updated Uno packages to latest version, removed WPF head from All solution

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR updates Uno packages to the latest stable version. 

Due to a mountain of issues caused by the WPF head after updating, @michael-hawker and I have opted to simply remove the head from the "All" solution for now as it's not widely used. 

We can revisit adding a functional WPF head back as part of #256

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Removed entire instead of commenting out. #257 should make this very easy to add back later.

**Comment by michael-hawker** [comment]
@Arlodotexe I was updating the testspace config as well, as that's misconfigured. Since we're still having issues with the long path in the other PR, did you want to add that here or do as a separate PR? See this commit: https://github.com/CommunityToolkit/Labs-Windows/pull/211/commits/0ce49c32a0d76c3b74f172b1cddc8045161b5d1a

**Comment by Arlodotexe** [comment]
@michael-hawker I'll just cherry pick that onto a new branch and open a PR quick.

**Review by michael-hawker — APPROVED** [review]
Tested out in code spaces LGTM

**Pull request merged**
