### PR TITLE
FIX ICONS

### PR DESCRIPTION
**Pull request by Jay-o-Way**
@niels9001 can we stop this game already?

### CODE REVIEW

**Comment by niels9001** [comment]
> @niels9001 can we stop this game already?

Mistakes happen, no need for these comments in every topic.. Thanks for fixing it though!

**Review by niels9001 — APPROVED** [review]
Thanks! Will merge when CI checks pass!

**Comment by Jay-o-Way** [comment]
Somebody in your position should not be making mistakes like this. I shouldn't be cleaning up after you.

**Comment by michael-hawker** [comment]
@Jay-o-Way this isn't appropriate. We're all human, things happen. 

Appreciate you making a PR and correcting this issue here, but there's no reason to be rude.

**Pull request merged**
