### PR TITLE
Ported notifications component from 7.x

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR ports source code and unit tests for the Notifications component from 7.x.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Needs https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/217

**Comment by Arlodotexe** [comment]
Also needs https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/218

**Comment by Arlodotexe** [comment]
Could make use https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/101, but doesn't strictly need it to close this PR.

**Review by Sergio0694 — APPROVED** [review]
Ship it!

**Pull request merged**
