### PR TITLE
Trivia handling

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Review by Sergio0694 — COMMENTED** [review]
Added some comments and fixed the merge conflict. I'm getting test failures though 🥲

image

Thoughts?

**Comment by Youssef1313** [comment]
@Sergio0694 Sorry not home right now. I will check when I get back. I tested my change with one test only unfortunately.

I'd **guess** there may be some syntax editor call that should use the lambda overload to fix that error.

**Comment by Youssef1313** [comment]
@Sergio0694 It should hopefully be better now

**Comment by Sergio0694** [comment]
@Youssef1313 works great, thank you!! 😄

**Pull request merged**
