### PR TITLE
Alzollin/markdown features

### PR DESCRIPTION
**Pull request by azchohfi**

### CODE REVIEW

**Review by Arlodotexe — COMMENTED** [review]
Most of these changes seem pretty good. My only concern is that we're routing the event for handling clicks via the config object, which makes it more difficult to set from XAML.

**Comment by azchohfi** [comment]
That is a fair point, but isn't that true for any property on the config? I did it this way since it wasn't that straightforward to add it to the markdowntextblock itself, since we have no easy reference to it.

**Comment by Arlodotexe** [comment]
> That is a fair point, but isn't that true for any property on the config? I did it this way since it wasn't that straightforward to add it to the markdowntextblock itself, since we have no easy reference to it.

True, and anything on the config could be turned into a separate dependency property if we wanted binding support for the options.

The distinction seems to be that the config options (custom svg renderer, image provider) are a bit more advanced than a `LinkClicked` handler. These would likely need to be set up in code-behind anyway, whereas you might expect `LinkClicked` to show when declaring the type in XAML.

**Comment by Arlodotexe** [comment]
This is also the behavior from the 7.x version of our `MarkdownTextBlock`.

**Comment by azchohfi** [comment]
You are right. Done.

**Review by Arlodotexe — APPROVED** [review]
Great work! This will see plenty of usage and brings us closer to feature parity with the 7.x control. Let's ship it 🚀

**Comment by nerocui** [comment]
Nice set of changes! Are we merging this soon?

**Comment by michael-hawker** [comment]
@azchohfi would you have a chance to rebase this PR? Then we can merge:

image

I tried locally, but there are conflicting changes with your other PR #586 that I'm not 100% confident in resolving in MyHyperlinkButton.cs within the constructor.

**Comment by michael-hawker** [comment]
Ah I see the conflict is from https://github.com/CommunityToolkit/Labs-Windows/pull/587 - that maybe helps as that is simple. I'll see if I can rebase this myself again.

**Comment by michael-hawker** [comment]
Alright, all fixed! Set to auto-merge once the CI passes, thanks folks!

**Pull request merged**
