### PR TITLE
🚧 Add check for VM to test for Longpath

### PR DESCRIPTION
**Pull request by michael-hawker**
Doing a test to see if windows latest vm has long path enabled already, see https://github.com/actions/virtual-environments/issues/1052

### CODE REVIEW

**Comment by michael-hawker** [comment]
@Arlodotexe I'm more confused now, looks like long paths are already enabled... @jeromelaban any ideas on what's going on with the DirectoryNotFound long path for the Xamarin generator?

https://github.com/CommunityToolkit/Labs-Windows/pull/211#issuecomment-1190825280

> D:\a\Labs-Windows\Labs-Windows\labs\StackedNotificationsBehavior\samples\StackedNotificationsBehavior.Samples\obj\Release\xamarinios10\g\NativeCtorsGenerator\StackedNotificationsBehaviorExperiment_Samples_StackedNotificationsBehaviorCustomSample_3aca12002872ed9de2d15c6b3ebbd506.g.cs

**Comment by jeromelaban** [comment]
> @Arlodotexe I'm more confused now, looks like long paths are already enabled... @jeromelaban any ideas on what's going on with the DirectoryNotFound long path for the Xamarin generator?
> 

Yes, this is generally cause by the fact that Xamarin projects use Uno.SourceGenerationTasks because of their supported C# version (7.3, in general). Given VS 2022 is used, you can switch it to use Roslyn's embedded generation by adding this to the csproj files:
```xml
<PropertyGroup>
    <UnoUIUseRoslynSourceGenerators>true</UnoUIUseRoslynSourceGenerators>
</PropertyGroup>
```

Note that `Directory.Build.props` may not work as intended in the case of legacy projects, requiring to place this property in all xamarin project files.

**Comment by michael-hawker** [comment]
@Arlodotexe I know you were tinkering with updating Uno to the latest version as well. Did you try this `UnoUIUseRoslynSourceGenerators` flag their as well?

```xml
<PropertyGroup>
    <UnoUIUseRoslynSourceGenerators>true</UnoUIUseRoslynSourceGenerators>
</PropertyGroup>
```

I know we had some concerns on overlapping source generators between Uno and Labs, eh?

**Comment by michael-hawker** [comment]
Closing this as we now know the VMs already have long-path support enabled, so that's not the issue. Trying some things out in the #211 PR now.

**Pull request closed without merging**
