### PR TITLE
Remove package ID from Segmented/Shimmer

### PR DESCRIPTION
**Pull request by niels9001**

### CODE REVIEW

**Comment by michael-hawker** [comment]
@Arlodotexe need you to explain to me what's going on here and why our build is passing but the new controls aren't getting packed... this is part of the template:

https://github.com/CommunityToolkit/Labs-Windows/blob/9d435734e3293d0d7c786286f5def668c5f0a990/template/ProjectTemplate/src/CommunityToolkit.Labs.WinUI.ProjectTemplate.csproj#L4

But only Segmented an Shimmer have it:

https://github.com/CommunityToolkit/Labs-Windows/blob/9d435734e3293d0d7c786286f5def668c5f0a990/components/Shimmer/src/CommunityToolkit.Labs.WinUI.Shimmer.csproj#L4

Which if this is the problem (as I think you mentioned)... why is it in the template still?

Can we quickly get a PR that fixes the template and all the things in the repo to be consistent? Possible via this PR of @niels9001, as it's got 1/3rd of the things? Can you confirm the expectations here for posterity? Thanks!

**Comment by michael-hawker** [comment]
I'd like to understand later too if this causes an error locally in packing why it doesn't show up as an error in packing in the CI?

**Comment by Arlodotexe** [comment]
> @Arlodotexe need you to explain to me what's going on here and why our build is passing but the new controls aren't getting packed... this is part of the template:
> 
> https://github.com/CommunityToolkit/Labs-Windows/blob/9d435734e3293d0d7c786286f5def668c5f0a990/template/ProjectTemplate/src/CommunityToolkit.Labs.WinUI.ProjectTemplate.csproj#L4
> 
> But only Segmented an Shimmer have it:
> 
> https://github.com/CommunityToolkit/Labs-Windows/blob/9d435734e3293d0d7c786286f5def668c5f0a990/components/Shimmer/src/CommunityToolkit.Labs.WinUI.Shimmer.csproj#L4
> 
> Which if this is the problem (as I think you mentioned)... why is it in the template still?
> 
> Can we quickly get a PR that fixes the template and all the things in the repo to be consistent? Possible via this PR of @niels9001, as it's got 1/3rd of the things? Can you confirm the expectations here for posterity? Thanks!

These changes and the fix we need to unblock publishing to nuget is included in #394, which is ready to merge when the CI passes.

**Review by michael-hawker — APPROVED** [review]

**Comment by michael-hawker** [comment]
@Arlodotexe #394 is still building and missing the change to the newly merged Shimmer control (we'll need to audit any other open component PRs for this).

Going to merge this one first, as we don't know if #394 has a clean build yet.

**Pull request merged**
