### PR TITLE
Rename common directory to tooling

### PR DESCRIPTION
**Pull request by michael-hawker**
Draft request to test CI, needs to wait for #403 to be merged first (and then this PR needs to be rebased).

This PR:
- moves `common` to `tooling`
- creates a `ToolingDirectory` property
- creates a couple of env in build.yml

Basically makes it easier to configure/change later without having to be hard-coded, but not completely yet. But enough while I was swapping many things out anyway.

### CODE REVIEW

**Comment by michael-hawker** [comment]
Looks like I missed something somewhere:
```
Run ./tooling/GenerateAllSolution.ps1
GenerateAllSolution.ps1: /home/runner/work/_temp/[12](https://github.com/CommunityToolkit/Labs-Windows/actions/runs/4409554861/jobs/7725992269#step:6:13)7296b3-46ca-4774-bb0c-8f97dc817ab7.ps1:2
Line |
   2 |  ./tooling/GenerateAllSolution.ps1
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term './common/MultiTarget/GenerateAllProjectReferences.ps1' is not
     | recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included,
     | verify that the path is correct and try again.
```

```
8s
Run powershell -version 5.[1](https://github.com/CommunityToolkit/Labs-Windows/actions/runs/4409554861/jobs/7726023837#step:9:1) -command "./tooling/GenerateAllSolution.ps1 -IncludeHeads UWP" -ErrorAction Stop
D:\a\Labs-Windows\Labs-Windows\tooling\GenerateAllSolution.ps1 : The term 
'./common/MultiTarget/GenerateAllProjectReferences.ps1' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At line:1 char:1
+ ./tooling/GenerateAllSolution.ps1 -IncludeHeads UWP -ErrorAction Stop
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./common/MultiT...tReferences.ps1:String) [GenerateAllSolution.ps1], Co 
   mmandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,GenerateAllSolution.ps1
```

**Comment by michael-hawker** [comment]
Error was the .NET Native memory one in the pipeline... need to rebase anyway, doing that now.

**Review by Arlodotexe — APPROVED** [review]
Approved, looks good as long as CI passes! Glad to see we parameterized the tooling directory as well 🙂

**Comment by michael-hawker** [comment]
> Approved, looks good as long as CI passes! Glad to see we parameterized the tooling directory as well 🙂

Awesome, thanks! Yeah, it's not completely parameterized yet, but figured I'd start us down that path, that way in the future eventually it'll just be something that's a prop variable somewhere or something and can be changed. At least until we get to a package or something setup instead.

**Comment by michael-hawker** [comment]
Hitting #245 with this constantly for some reason, spun up #406 to see if that helps there at all...

**Pull request merged**
